name: Deploy Flask App

on:
  push:
    branches:
      - main    # When you push to the main branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # or your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask App (Test Locally)
      run: |
        echo "FLASK_APP=app.py" > .env
        flask run --host=0.0.0.0 --port=5000
